- name: Download foo.conf
  get_url:
    url: "{{ url }}"
    dest: "{{ dest1 }}"

- name: Extract file
  unarchive:
    src: "{{ src1 }}"
    dest: "{{ dest2 }}"
    remote_src: yes 

- name: Copy file with owner and permissions
  copy:
    src: "{{ src2 }}"
    dest: "{{ dest3 }}"
    owner: apache
    group: apache
    mode: '0755'
    remote_src: yes 

- name: Restart Apache
  service: 
    name: "{{ name1 }}"
    state: "{{ status }}"