- name: Start mariadb
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Create a new database 
  community.mysql.mysql_db:
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    name: "{{ db_name }}"
    state: present

- name: Create database user with name '{{ db_user }}' and password '{{ db_password }}' with all database privileges
  community.mysql.mysql_user:
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    state: present
    column_case_sensitive: false